// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	collections "github.com/linesmerrill/police-cad-api/mongodb"

	mock "github.com/stretchr/testify/mock"
)

// CollectionHelper is an autogenerated mock type for the CollectionHelper type
type CollectionHelper struct {
	mock.Mock
}

// FindOne provides a mock function with given fields: _a0, _a1
func (_m *CollectionHelper) FindOne(_a0 context.Context, _a1 interface{}) collections.SingleResultHelper {
	ret := _m.Called(_a0, _a1)

	var r0 collections.SingleResultHelper
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) collections.SingleResultHelper); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(collections.SingleResultHelper)
		}
	}

	return r0
}
