// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	collections "github.com/linesmerrill/police-cad-api/mongodb"
	mock "github.com/stretchr/testify/mock"
)

// DatabaseHelper is an autogenerated mock type for the DatabaseHelper type
type DatabaseHelper struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *DatabaseHelper) Client() collections.ClientHelper {
	ret := _m.Called()

	var r0 collections.ClientHelper
	if rf, ok := ret.Get(0).(func() collections.ClientHelper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(collections.ClientHelper)
		}
	}

	return r0
}

// Collection provides a mock function with given fields: name
func (_m *DatabaseHelper) Collection(name string) collections.CollectionHelper {
	ret := _m.Called(name)

	var r0 collections.CollectionHelper
	if rf, ok := ret.Get(0).(func(string) collections.CollectionHelper); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(collections.CollectionHelper)
		}
	}

	return r0
}
