// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	databases "github.com/linesmerrill/police-cad-api/databases"
	mock "github.com/stretchr/testify/mock"

	models "github.com/linesmerrill/police-cad-api/models"

	options "go.mongodb.org/mongo-driver/mongo/options"
)

// CommunityDatabase is an autogenerated mock type for the CommunityDatabase type
type CommunityDatabase struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, filter, opts
func (_m *CommunityDatabase) Find(ctx context.Context, filter interface{}, opts ...*options.FindOptions) databases.MongoCursor {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 databases.MongoCursor
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOptions) databases.MongoCursor); ok {
		r0 = rf(ctx, filter, opts...)
	} else {
		r0 = ret.Get(0).(databases.MongoCursor)
	}

	return r0
}

// FindOne provides a mock function with given fields: ctx, filter
func (_m *CommunityDatabase) FindOne(ctx context.Context, filter interface{}) (*models.Community, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *models.Community
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) (*models.Community, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) *models.Community); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Community)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertOne provides a mock function with given fields: ctx, community, opts
func (_m *CommunityDatabase) InsertOne(ctx context.Context, community models.Community, opts ...*options.InsertOneOptions) databases.InsertOneResultHelper {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, community)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InsertOne")
	}

	var r0 databases.InsertOneResultHelper
	if rf, ok := ret.Get(0).(func(context.Context, models.Community, ...*options.InsertOneOptions) databases.InsertOneResultHelper); ok {
		r0 = rf(ctx, community, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(databases.InsertOneResultHelper)
		}
	}

	return r0
}

// UpdateOne provides a mock function with given fields: ctx, filter, update, opts
func (_m *CommunityDatabase) UpdateOne(ctx context.Context, filter interface{}, update interface{}, opts ...*options.UpdateOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter, update)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) error); ok {
		r0 = rf(ctx, filter, update, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommunityDatabase creates a new instance of CommunityDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommunityDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommunityDatabase {
	mock := &CommunityDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
