// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CursorHelper is an autogenerated mock type for the CursorHelper type
type CursorHelper struct {
	mock.Mock
}

// Decode provides a mock function with given fields: v
func (_m *CursorHelper) Decode(v interface{}) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCursorHelper creates a new instance of CursorHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCursorHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *CursorHelper {
	mock := &CursorHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
