// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/linesmerrill/police-cad-api/models"
)

// EMSPersonaDatabase is an autogenerated mock type for the EMSPersonaDatabase type
type EMSPersonaDatabase struct {
	mock.Mock
}

// CreateEMSPersona provides a mock function with given fields: ctx, persona
func (_m *EMSPersonaDatabase) CreateEMSPersona(ctx context.Context, persona *models.EMSPersona) error {
	ret := _m.Called(ctx, persona)

	if len(ret) == 0 {
		panic("no return value specified for CreateEMSPersona")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.EMSPersona) error); ok {
		r0 = rf(ctx, persona)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteEMSPersona provides a mock function with given fields: ctx, id
func (_m *EMSPersonaDatabase) DeleteEMSPersona(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEMSPersona")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEMSPersonaByID provides a mock function with given fields: ctx, id
func (_m *EMSPersonaDatabase) GetEMSPersonaByID(ctx context.Context, id string) (*models.EMSPersona, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEMSPersonaByID")
	}

	var r0 *models.EMSPersona
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.EMSPersona, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.EMSPersona); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EMSPersona)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEMSPersonasByCommunityID provides a mock function with given fields: ctx, activeCommunityID, userID, limit, page
func (_m *EMSPersonaDatabase) GetEMSPersonasByCommunityID(ctx context.Context, activeCommunityID string, userID string, limit int64, page int64) (*models.EMSPersonaResponse, error) {
	ret := _m.Called(ctx, activeCommunityID, userID, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetEMSPersonasByCommunityID")
	}

	var r0 *models.EMSPersonaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) (*models.EMSPersonaResponse, error)); ok {
		return rf(ctx, activeCommunityID, userID, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) *models.EMSPersonaResponse); ok {
		r0 = rf(ctx, activeCommunityID, userID, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EMSPersonaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, int64) error); ok {
		r1 = rf(ctx, activeCommunityID, userID, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEMSPersona provides a mock function with given fields: ctx, id, persona
func (_m *EMSPersonaDatabase) UpdateEMSPersona(ctx context.Context, id string, persona *models.EMSPersona) error {
	ret := _m.Called(ctx, id, persona)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEMSPersona")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.EMSPersona) error); ok {
		r0 = rf(ctx, id, persona)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEMSPersonaDatabase creates a new instance of EMSPersonaDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEMSPersonaDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *EMSPersonaDatabase {
	mock := &EMSPersonaDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
