// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/linesmerrill/police-cad-api/models"
)

// EMSVehicleDatabase is an autogenerated mock type for the EMSVehicleDatabase type
type EMSVehicleDatabase struct {
	mock.Mock
}

// CreateEMSVehicle provides a mock function with given fields: ctx, vehicle
func (_m *EMSVehicleDatabase) CreateEMSVehicle(ctx context.Context, vehicle *models.EMSVehicle) error {
	ret := _m.Called(ctx, vehicle)

	if len(ret) == 0 {
		panic("no return value specified for CreateEMSVehicle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.EMSVehicle) error); ok {
		r0 = rf(ctx, vehicle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteEMSVehicle provides a mock function with given fields: ctx, id
func (_m *EMSVehicleDatabase) DeleteEMSVehicle(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEMSVehicle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEMSVehicleByID provides a mock function with given fields: ctx, id
func (_m *EMSVehicleDatabase) GetEMSVehicleByID(ctx context.Context, id string) (*models.EMSVehicle, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEMSVehicleByID")
	}

	var r0 *models.EMSVehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.EMSVehicle, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.EMSVehicle); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EMSVehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEMSVehiclesByCommunityID provides a mock function with given fields: ctx, activeCommunityID, userID, limit, page
func (_m *EMSVehicleDatabase) GetEMSVehiclesByCommunityID(ctx context.Context, activeCommunityID string, userID string, limit int64, page int64) (*models.EMSVehicleResponse, error) {
	ret := _m.Called(ctx, activeCommunityID, userID, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetEMSVehiclesByCommunityID")
	}

	var r0 *models.EMSVehicleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) (*models.EMSVehicleResponse, error)); ok {
		return rf(ctx, activeCommunityID, userID, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) *models.EMSVehicleResponse); ok {
		r0 = rf(ctx, activeCommunityID, userID, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EMSVehicleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, int64) error); ok {
		r1 = rf(ctx, activeCommunityID, userID, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEMSVehicle provides a mock function with given fields: ctx, id, vehicle
func (_m *EMSVehicleDatabase) UpdateEMSVehicle(ctx context.Context, id string, vehicle *models.EMSVehicle) error {
	ret := _m.Called(ctx, id, vehicle)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEMSVehicle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.EMSVehicle) error); ok {
		r0 = rf(ctx, id, vehicle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEMSVehicleDatabase creates a new instance of EMSVehicleDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEMSVehicleDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *EMSVehicleDatabase {
	mock := &EMSVehicleDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
