// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InsertOneResultHelper is an autogenerated mock type for the InsertOneResultHelper type
type InsertOneResultHelper struct {
	mock.Mock
}

// Decode provides a mock function with given fields:
func (_m *InsertOneResultHelper) Decode() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// NewInsertOneResultHelper creates a new instance of InsertOneResultHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInsertOneResultHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *InsertOneResultHelper {
	mock := &InsertOneResultHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
