// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/linesmerrill/police-cad-api/models"
)

// MedicationDatabase is an autogenerated mock type for the MedicationDatabase type
type MedicationDatabase struct {
	mock.Mock
}

// CreateMedication provides a mock function with given fields: ctx, medication
func (_m *MedicationDatabase) CreateMedication(ctx context.Context, medication *models.Medication) error {
	ret := _m.Called(ctx, medication)

	if len(ret) == 0 {
		panic("no return value specified for CreateMedication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Medication) error); ok {
		r0 = rf(ctx, medication)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMedication provides a mock function with given fields: ctx, id
func (_m *MedicationDatabase) DeleteMedication(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMedication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMedicationByID provides a mock function with given fields: ctx, id
func (_m *MedicationDatabase) GetMedicationByID(ctx context.Context, id string) (*models.Medication, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMedicationByID")
	}

	var r0 *models.Medication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Medication, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Medication); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Medication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMedicationsByCivilianID provides a mock function with given fields: ctx, civilianID, activeCommunityID, limit, page
func (_m *MedicationDatabase) GetMedicationsByCivilianID(ctx context.Context, civilianID string, activeCommunityID string, limit int64, page int64) (*models.MedicationResponse, error) {
	ret := _m.Called(ctx, civilianID, activeCommunityID, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetMedicationsByCivilianID")
	}

	var r0 *models.MedicationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) (*models.MedicationResponse, error)); ok {
		return rf(ctx, civilianID, activeCommunityID, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) *models.MedicationResponse); ok {
		r0 = rf(ctx, civilianID, activeCommunityID, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MedicationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, int64) error); ok {
		r1 = rf(ctx, civilianID, activeCommunityID, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMedication provides a mock function with given fields: ctx, id, medication
func (_m *MedicationDatabase) UpdateMedication(ctx context.Context, id string, medication *models.Medication) error {
	ret := _m.Called(ctx, id, medication)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMedication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Medication) error); ok {
		r0 = rf(ctx, id, medication)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMedicationDatabase creates a new instance of MedicationDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMedicationDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MedicationDatabase {
	mock := &MedicationDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
