// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/linesmerrill/police-cad-api/models"
)

// MedicalReportDatabase is an autogenerated mock type for the MedicalReportDatabase type
type MedicalReportDatabase struct {
	mock.Mock
}

// CreateMedicalReport provides a mock function with given fields: ctx, medicalReport
func (_m *MedicalReportDatabase) CreateMedicalReport(ctx context.Context, medicalReport *models.MedicalReport) error {
	ret := _m.Called(ctx, medicalReport)

	if len(ret) == 0 {
		panic("no return value specified for CreateMedicalReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MedicalReport) error); ok {
		r0 = rf(ctx, medicalReport)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMedicalReport provides a mock function with given fields: ctx, id
func (_m *MedicalReportDatabase) DeleteMedicalReport(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMedicalReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMedicalReportByID provides a mock function with given fields: ctx, id
func (_m *MedicalReportDatabase) GetMedicalReportByID(ctx context.Context, id string) (*models.MedicalReport, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMedicalReportByID")
	}

	var r0 *models.MedicalReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.MedicalReport, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.MedicalReport); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MedicalReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMedicalReportsByCivilianID provides a mock function with given fields: ctx, civilianID, activeCommunityID, limit, page
func (_m *MedicalReportDatabase) GetMedicalReportsByCivilianID(ctx context.Context, civilianID string, activeCommunityID string, limit int64, page int64) (*models.MedicalReportResponse, error) {
	ret := _m.Called(ctx, civilianID, activeCommunityID, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetMedicalReportsByCivilianID")
	}

	var r0 *models.MedicalReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) (*models.MedicalReportResponse, error)); ok {
		return rf(ctx, civilianID, activeCommunityID, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) *models.MedicalReportResponse); ok {
		r0 = rf(ctx, civilianID, activeCommunityID, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MedicalReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, int64) error); ok {
		r1 = rf(ctx, civilianID, activeCommunityID, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMedicalReport provides a mock function with given fields: ctx, id, medicalReport
func (_m *MedicalReportDatabase) UpdateMedicalReport(ctx context.Context, id string, medicalReport *models.MedicalReport) error {
	ret := _m.Called(ctx, id, medicalReport)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMedicalReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.MedicalReport) error); ok {
		r0 = rf(ctx, id, medicalReport)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMedicalReportDatabase creates a new instance of MedicalReportDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMedicalReportDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MedicalReportDatabase {
	mock := &MedicalReportDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
