// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SessionHelper is an autogenerated mock type for the SessionHelper type
type SessionHelper struct {
	mock.Mock
}

// EndSession provides a mock function with given fields:
func (_m *SessionHelper) EndSession() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionHelper creates a new instance of SessionHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionHelper {
	mock := &SessionHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
